---
- name: copy repo to /etc/yum-repos.d/
  copy:
    src: files/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install containerd separately (CentOS 8).
  package:
    name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/{{ containerd_version }}
    state: present
  when: ansible_distribution_major_version | int == 8

- name: install docker-ce
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - device-mapper-persistent-data
      - lvm2
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Set swapinnes to 0 as written in best practice
  sysctl:
    name: vm.swappiness
    value: "0"
    state: present

- name: Set overcommit_memory to 1 as written in best practice
  sysctl:
    name: vm.overcommit_memory
    value: "1"
    state: present

- name: start docker and enable it
  service: name=docker state=started enabled=yes

- name: install python-pip
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - python3-devel

- name: Install python library docker
  pip:
    name: docker

- name: Install and upgrade pip
  pip:
    name: pip
    extra_args: --upgrade

- name: Install docker-compose
  pip:
    name: docker-compose